### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain_core'

### ISSUE THREAD

**Issue by hturkcom** [Azzedde/paper_to_podcast#4]
Hi, Thank you for sharing your knowledge. However, I was unable to run the test podcast. I have already installed all the required modules, but I'm still encountering the following error:

python paper_to_podcast.py /root/paper_to_podcast/sample_papers/1729849776126.pdf
Traceback (most recent call last):
  File "/root/paper_to_podcast/paper_to_podcast.py", line 3, in <module>
    from templates import enhance_prompt, initial_dialogue_prompt, plan_prompt
  File "/root/paper_to_podcast/templates.py", line 1, in <module>
    from langchain_core.prompts import ChatPromptTemplate
ModuleNotFoundError: No module named 'langchain_core'

Proved that the module is already installed:
pip show langchain_chroma
how langchain_community
pip show langchain_core
pip show langchain_openai
pip show langchain_text_splitters
pip show openai
pip show pydub
pip show PyPDF2
pip show python-dotenv
Name: langchain-chroma
Version: 0.1.4
Summary: An integration package connecting Chroma and LangChain
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: chromadb, fastapi, langchain-core, numpy
Required-by:
(base) root@Linux:~/paper_to_podcast# pip show langchain_community
Name: langchain-community
Version: 0.3.3
Summary: Community contributed LangChain integrations.
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: aiohttp, dataclasses-json, langchain, langchain-core, langsmith, numpy, pydantic-settings, PyYAML, requests, SQLAlchemy, tenacity
Required-by:
(base) root@Linux:~/paper_to_podcast# pip show langchain_core
Name: langchain-core
Version: 0.3.13
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: jsonpatch, langsmith, packaging, pydantic, PyYAML, tenacity, typing-extensions
Required-by: langchain, langchain-chroma, langchain-community, langchain-openai, langchain-text-splitters
(base) root@Linux:~/paper_to_podcast# pip show langchain_openai
Name: langchain-openai
Version: 0.2.3
Summary: An integration package connecting OpenAI and LangChain
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: langchain-core, openai, tiktoken
Required-by:
(base) root@Linux:~/paper_to_podcast# pip show langchain_text_splitters
Name: langchain-text-splitters
Version: 0.3.0
Summary: LangChain text splitting utilities
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: langchain-core
Required-by: langchain
(base) root@Linux:~/paper_to_podcast# pip show openai
Name: openai
Version: 1.52.2
Summary: The official Python library for the openai API
Home-page: https://github.com/openai/openai-python
Author:
Author-email: OpenAI <support@openai.com>
License:
Location: /usr/local/lib/python3.10/dist-packages
Requires: anyio, distro, httpx, jiter, pydantic, sniffio, tqdm, typing-extensions
Required-by: langchain-openai
(base) root@Linux:~/paper_to_podcast# pip show pydub
Name: pydub
Version: 0.25.1
Summary: Manipulate audio with an simple and easy high level interface
Home-page: http://pydub.com
Author: James Robert
Author-email: jiaaro@gmail.com
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires:
Required-by: gradio, rvc-beta
(base) root@Linux:~/paper_to_podcast# pip show PyPDF2
Name: PyPDF2
Version: 3.0.1
Summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
Home-page:
Author:
Author-email: Mathieu Fenniak <biziqe@mathieu.fenniak.net>
License:
Location: /usr/local/lib/python3.10/dist-packages
Requires:
Required-by: demisto-sdk
(base) root@Linux:~/paper_to_podcast# pip show python-dotenv
Name: python-dotenv
Version: 1.0.1
Summary: Read key-value pairs from a .env file and set them as environment variables
Home-page: https://github.com/theskumar/python-dotenv
Author: Saurabh Kumar
Author-email: me+github@saurabh-kumar.com
License: BSD-3-Clause
Location: /usr/local/lib/python3.10/dist-packages
Requires:
Required-by: pydantic-settings

**Comment by Azzedde** [comment]
Hey ! Thanks for you interest in the project and sorry for the error you are encountering. There were indeed some bugs that I fixed in the project, but nothing related to "Module not existing langchain_core" :(
I have done the following steps from my side:
0. Ensure that you have python ^3.10
1. Created a venv: python3 -m venv .venv
2. Activated it: source .venv/bin/activate
3. Installed requirements: pip install -r requirements.txt
4. Run the script normally and generated an article: python3 paper_to_podcast.py ./sample_papers/2410.19706.pdf
Can you provide more information about your case, can you try exactly what I did and come back to me about how it went ?

**Comment by hturkcom** [comment]
Hi @Azzedde , Thank you for the steps. However, I’m still encountering errors. I have also set .env with OPENAI_API_KEY=KEY.

(.venv) (base) root@Linux:~/paper_to_podcast# nano .env
(.venv) (base) root@Linux:~/paper_to_podcast# python3.10
python3.10         python3.10-config
(.venv) (base) root@Linux:~/paper_to_podcast# python3.10 paper_to_podcast.py sample_papers/
1729849776126.pdf  1730113104257.pdf  2407.21783v2.pdf   2410.19706.pdf
(.venv) (base) root@Linux:~/paper_to_podcast# python3.10 paper_to_podcast.py sample_papers/1730113104257.pdf
Traceback (most recent call last):
  File "/root/paper_to_podcast/paper_to_podcast.py", line 7, in <module>
    from langchain_openai import ChatOpenAI
  File "/usr/local/lib/python3.10/dist-packages/langchain_openai/__init__.py", line 1, in <module>
    from langchain_openai.chat_models import AzureChatOpenAI, ChatOpenAI
  File "/usr/local/lib/python3.10/dist-packages/langchain_openai/chat_models/__init__.py", line 1, in <module>
    from langchain_openai.chat_models.azure import AzureChatOpenAI
  File "/usr/local/lib/python3.10/dist-packages/langchain_openai/chat_models/azure.py", line 10, in <module>
    from langchain_core.language_models.chat_models import LangSmithParams
ImportError: cannot import name 'LangSmithParams' from 'langchain_core.language_models.chat_models' (/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py)

**Comment by Azzedde** [comment]
I'm really happy that your previous problem is solved (I hope so), now let's focus on this new problem.
I don't really have an idea on what's happening on your side, can you give me more context about what your .venv have (use pip freeze and copy it in here), also are you working on Azure ? and lastly are you modifying things from your side ? (for example are you adding LangSmith monitoring ?) if you're not adding anything then check this issue here : https://github.com/langchain-ai/langchain/issues/24533 the author at a certain point had the same problem as you and he had conflicting packages.
Try to delete the .venv, delte the repo of the project, and reclone it on a new directory and recreate a new .venv that have python 3.10
Here to help you with this, you can do it !

**Comment by hturkcom** [comment]
Hi @Azzedde, Thank you for the advice; this worked for me! The entire setup is detailed below:

Remove the Existing .venv:

rm -rf .venv

Create a New Virtual Environment with Python 3.10:

python3.10 -m venv .venv

Activate the New Virtual Environment:

source .venv/bin/activate

Clone this repository:

git clone https://github.com/Azzedde/paper_to_podcast.git

Move into the project directory:

cd paper_to_podcast

Install Dependencies: Once activated, install the required dependencies:

pip install -r requirements.txt

Set the OPENAI API key in the .env file:

nano .env

Add this line:
OPENAI_API_KEY=MY-OPEN-AI-API-KEY

Run the Script: With the new environment active, run the Python script:

python3.10 paper_to_podcast.py sample_papers/1729849776126.pdf

**Comment by Azzedde** [comment]
I'm more than happy to hear that it worked for you ! Thanks again for your interest in the project, enjoy the podcasts !!!!

**Comment by hturkcom** [comment]
Thank you @Azzedde sharing this awesome project. I might modify your code to use a different AI provider (such as Gemini, Claude, or Mistral) instead of OpenAI. This is because I'm encountering an openai.RateLimitError with error code 429, indicating insufficient quota: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
