### ISSUE TITLE
some enhancement proposal to troubleshoot some common issues

### ISSUE THREAD

**Issue by MathFrenchToast** [Azzedde/paper_to_podcast#6]
I faced some issues,
I propose the following enhancement:

in requirements.txt, to jump to latest releases (tested ok)
```
langchain_chroma>=0.1.4
langchain_community>=0.3.10
langchain_core>=0.3.22
langchain_openai>=0.2.11
langchain_text_splitters>=0.3.2
openai>=1.55.3
pydub>=0.25.1
PyPDF>=3.1.0
python-dotenv==1.0.1
```

in script.py 
for error like can't decode byte 0x9d in position 2127, use utf-8 encoding
```
def initialize_discussion_chain(txt_file, llm):
    # Load, chunk and index the contents of the blog.
    loader = TextLoader(txt_file, encoding='UTF-8')
```

On windows system 
error ./podcast_20241209140110/host_2024-12-09 14:01:10.452134.mp3
this is because ':' is not allowed in filename
I propose to replace your `now` by `now = int(datetime.datetime.now().timestamp()) safe for every OS
in audio_gen.py

In the readme, propose to install ffmpeg and add it to the path if not present
I can fork and make a PR if preferred

**Comment by Azzedde** [comment]
Apologies for the inconveniences you're experiencing. I think creating a PR would be a fantastic idea—it would be greatly appreciated! Thank you for pointing this out. I'll make sure to merge it once you submit it. Thanks again!

**Comment by MathFrenchToast** [comment]
done, PR is : https://github.com/Azzedde/paper_to_podcast/pull/7

**Comment by Azzedde** [comment]
Thanks again, PR merged !
