### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by mohcenaouadj** [Azzedde/paper_to_podcast#8]
Hello Azzedine, great project indeed, can't wait to test it.

I'm not that expert when it comes to LLMs or NLP in general, yet when i try to test the project  I receive the following error : **API Key not found**. 
I understand that there must be some kind of access key to use the API, yet you haven't specified anything related to in your readme file, so how what you suggestion as a solution to this issue ?

Thanks.

**Comment by Azzedde** [comment]
**Hello Mohcene,**

Thank you for your interest in the project! I appreciate your question regarding the API key setup, as I didn’t go into much detail in the documentation about adding it to the `.env` file to ensure the project runs seamlessly.

As you may know, LLMs (Large Language Models) are complex neural networks that require significant computational resources to operate efficiently. While it’s possible to run an LLM on a CPU, it can be extremely slow. Thankfully, providers like OpenAI, Anthropic, and Google offer powerful LLMs accessible via their platforms. By subscribing to their services, you gain access through an API key. This key acts as a credential to authenticate your requests and ensure secure communication between you (the client) and the provider.

I recommend visiting the OpenAI website (or the relevant provider) to explore their guides and pricing models. Most providers offer free credits when you create an account, allowing you to test the project without any initial cost. However, once these free credits are depleted, you’ll need to pay to continue using their services.

To integrate your API key into the project, follow these steps:

1. Clone the repository.
2. In the project’s root directory, create a file named `.env`.
3. Add your API key in the following format:

   ```plaintext
   OPENAI_API_KEY="sk-123..."
   ```

Once this is done, the project should function smoothly.

Thanks again for reaching out! Don’t hesitate to ask if you encounter any other issues—I’m happy to help.

Best regards,  
Azzedine

**Comment by mohcenaouadj** [comment]
Thank you a lot for your help.

Cordially.
